db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost
  poolProperties:
    size: 12
    timeout: 10
  properties:
    first: 123
    second: 567
    third.value: Third
  pools:
  - size: 1
    timeout: 1
  - size: 2
    timeout: 2

logging:
  level:
    root: INFO
    com.example.spring2.ConnectionPool: INFO
  file:
    name: spring.log
    path: /
spring:
  datasource:
#    url: jdbc:postgresql://192.168.99.100:5433/postgres
    url: jdbc:postgresql://127.0.0.1:5433/db1
    username: postgres
    password: sadnasKFABFKAWFBAjk6135KBAFKAJB FAKLWJFN11354fafsefdxf3dx51351531fdxfdx1fdxf351531KUBJVJVBADKWDBAKDB
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

spring.profiles.active: qa
