db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost
  poolProperties:
    size: 12
    timeout: 10
  properties:
    first: 123
    second: 567
    third.value: Third
  pools:
  - size: 1
    timeout: 1
  - size: 2
    timeout: 2

spring.profiles.active: qa
logging:
  level:
    root: WARN
    com.example.spring2.ConnectionPool: INFO
  file:
    name: spring.log
    path: /